language: python
python: "3.7"

# virtualenv:
#   system_site_packages: true
services:
  - docker

# Install dependencies.
install:
  - pip install pipenv
  - pipenv install

# Do fake test.
script:
  - pipenv check

# Deploy to DH.
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master


